### ISSUE TITLE
Assignment2

### ISSUE THREAD

**Issue by AndreyIsakov01** [andikalovskiynd/HomeAssignments#3]
1) Изменить название Makefile'а на стандартное, чтобы можно было производить сборку просто командой make
2) Исправить отступы в Makefile

**Comment by vkats-spbu** [comment]
> 1. Изменить название Makefile'а на стандартное, чтобы можно было производить сборку просто командой make
> 
>     2. Исправить отступы в Makefile

<pre>victor@victor-VirtualBox:~/accesment/andikalovskiynd/HomeAssignments/Assignment2$ make
Makefile:2: *** missing separator.  Stop.
</pre>
